spring:
  profiles:
    active: ${ENV:local} # sets `local` as the default active profile

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - mappings
          - health
          - env
          - liquibase
          - beans
          - loggers
          - prometheus
  info:
    git:
      mode: full